<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('properties')->insert([
            [
                'location' => '123 Main St',
                'description' => '',
                'year' => 1920,
                'size' => 150,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'agent_id' => 1,
                'city_id' => 1,
                'type_id' => 1,
                'image' => '',
                'price' => 1500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '789 Maple Blvd',
                'description' => '',
                'year' => 1980,
                'size' => 200,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'agent_id' => 3,
                'city_id' => 3,
                'type_id' => 1,
                'image' => '',
                'price' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '1010 Beach Dr',
                'description' => '',
                'year' => 1995,
                'size' => 500,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'agent_id' => 4,
                'city_id' => 4,
                'type_id' => 1,
                'image' => '',
                'price' => 3500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '17 Rue de Rivoli',
                'description' => '',
                'year' => 1905,
                'size' => 80,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'agent_id' => 5,
                'city_id' => 5,
                'type_id' => 2,
                'image' => '',
                'price' => 1000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '35 St. James Square',
                'description' => '',
                'year' => 1990,
                'size' => 300,
                'bedrooms' => 6,
                'bathrooms' => 4,
                'agent_id' => 6,
                'city_id' => 6,
                'type_id' => 1,
                'image' => '',
                'price' => 10000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '123 Main St',
                'description' => '',
                'year' => 1925,
                'size' => 150,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'agent_id' => 1,
                'city_id' => 3,
                'type_id' => 1,
                'image' => '',
                'price' => 1200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '789 Maple Dr',
                'description' => '',
                'year' => 1950,
                'size' => 300,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'agent_id' => 2,
                'city_id' => 2,
                'type_id' => 1,
                'image' => '',
                'price' => 2500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '456 Pine St',
                'description' => '',
                'year' => 1930,
                'size' => 250,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'agent_id' => 3,
                'city_id' => 3,
                'type_id' => 1,
                'image' => '',
                'price' => 1800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '987 Ocean Blvd',
                'description' => '',
                'year' => 2015,
                'size' => 200,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'agent_id' => 4,
                'city_id' => 4,
                'type_id' => 2,
                'image' => '',
                'price' => 1600000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '555 Madison Ave',
                'description' => '',
                'year' => 1980,
                'size' => 500,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'agent_id' => 5,
                'city_id' => 1,
                'type_id' => 1,
                'image' => '',
                'price' => 5000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '456 Cherry St',
                'description' => '',
                'year' => 1950,
                'size' => 150,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'agent_id' => 6,
                'city_id' => 3,
                'type_id' => 2,
                'image' => '',
                'price' => 900000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location' => '456 Oak Ave',
                'description' => '',
                'year' => 2016,
                'size' => 100,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'agent_id' => 2,
                'city_id' => 2,
                'type_id' => 2,
                'image' => '',
                'price' => 750000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
